echo '*********************************************************************************************************'
echo 'ISSUES IN DEPLOYMENT'
echo '---------------------------------------------------------------------------------------------------------'
echo 'Total Count: 0'
echo '---------------------------------------------------------------------------------------------------------'
echo 'ISSUES IN main BRANCH'
echo '---------------------------------------------------------------------------------------------------------'
echo 'Total Count: 1'
echo '---------------------------------------------------------------------------------------------------------'
echo '⚠ ISSUE#1- ml5js does not have an available @types to package js code as @Injectable Service'
echo '_________________________________________________________________________________________________________'
echo 'PROGRESS DISCUSSION'
echo 'Œ BTR - Evaluating if replacing UI Component with js will solve this issue. If evaluation fails create'
echo 'base types for ml5 or use alternative with ts support'
echo '_________________________________________________________________________________________________________'
echo 'AFFECTED FILES'
echo 'src/profile-site/src/app/park/services/catdetector/catdetector.service.d.ts'
echo 'src/profile-site/src/app/park/services/catdetector/catdetector.service.js'
echo 'src/profile-site/src/app/park/park.component.ts'
echo '_________________________________________________________________________________________________________'
echo '---------------------------------------------------------------------------------------------------------'
echo '*********************************************************************************************************'
echo ' '
echo 'Typescript SPA root for profile in src/profile-site'
echo 'cd /src/profile-site'
echo 'For generating a build to update github.io site:'
echo 'npm run git-build'
echo 'copy build deliverables from dist of angular to <root>/docs'
echo 'To run the project:'
echo 'ng serve'
